repositories:
  - name: kyverno
    url: https://kyverno.github.io/kyverno/

releases:
  - name: kyverno
    chart: kyverno/kyverno
    namespace: kyverno
    createNamespace: true
    wait: true
    waitForJobs: true
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "../manifests"]
      - events: ["postsync"]
        showlogs: true
        command: "/bin/bash"
        args: ["-c", "until ../scripts/kyverno-ready.sh; do sleep 3; done"]
        
  - name: nats
    chart: oci://registry-1.docker.io/bitnamicharts/nats
    version: 8.5.1
    createNamespace: true
    wait: true
    waitForJobs: true
    namespace: ssi 
    values:
      - values/nats.yaml
    needs:
      - kyverno/kyverno
   
  - name: gateway
    chart: ../charts/gateway
    createNamespace: true
    namespace: ssi
    values:
      - values/gateway.yaml
    needs:
      - kyverno/kyverno
      - nats

  - name: names-service
    chart: ../charts/names-service
    createNamespace: true
    namespace: ssi
    values:
      - values/names-service.yaml
    needs:
      - kyverno/kyverno
      - nats

  - name: verbs-service
    chart: ../charts/verbs-service
    createNamespace: true
    namespace: ssi
    values:
      - values/verbs-service.yaml
    needs:
      - kyverno/kyverno
      - nats
