apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}
data:
  NATS_HOST: {{ .Values.nats.host }}
  NATS_PORT: {{ .Values.nats.port | quote }}
  SERVER_PORT: {{ .Values.service.port | quote }}