
services:

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.NonRootUser
      target: prod
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./gateway/.env

  names-service:
    build:
      context: ./names-service
      dockerfile: Dockerfile.NonRootUser
      target: prod
    restart: always
    env_file:
      - ./names-service/.env

  verbes-service:
    build:
      context: ./verbs-service
      dockerfile: Dockerfile.NonRootUser
      target: prod
    restart: always
    env_file:
      - ./verbs-service/.env




